### ISSUE TITLE
누가 도배 싫댔는데 이게뭐죠

### ISSUE THREAD

**Issue by wjdgustn** [pikokr/pikokr#1]
![20210227_193954](https://user-images.githubusercontent.com/34962071/109384970-b8768480-7933-11eb-9fea-5f77b7806b82.png)

**Comment by paring-chan** [comment]
.

**Comment by wjdgustn** [comment]
여기서도 하시네요

**Comment by patrick-choe** [comment]
![Screenshot_20210227-193952_Discord](https://user-images.githubusercontent.com/32794309/109385013-10ad8680-7934-11eb-8ea3-f922326287e4.png)

증거 2222222222

**Comment by paring-chan** [comment]
아니이이이 뭘 너무 많이 시키니까 그렇죠오

**Comment by paring-chan** [comment]
으에엥

**Comment by patrick-choe** [comment]
그러니까 사실은 도배가 좋았던거라고요? 알겠습니다. PR 직성할게요.

**Comment by paring-chan** [comment]
아니야아아아아
